name: Validar HTML y CSS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar c√≥digo
        uses: actions/checkout@v4

      - name: Validar HTML (W3C)
        uses: Cyb3r-Jak3/html5validator-action@v3
        with:
          root: .
          blacklist: "node_modules"

      - name: Validar CSS
        run: |
          echo "Validando CSS..."
          for file in $(find . -name "*.css"); do
            echo "Archivo: $file"
            npx stylelint "$file" || true
          done
